name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Set up Docker
    - name: Set up Docker
      run: |
        docker --version
        docker-compose --version || echo "docker-compose not found" 

    # Install Docker Compose using official script
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version  # Check Docker Compose version

    # Build Docker image
    - name: Build Docker image
      run: |
        docker compose build

    # Run tests
    - name: Run tests
      run: |
        docker compose run --rm app pytest -v

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Lint with flake8
    - name: Lint with flake8
      run: |
        docker compose exec app flake8 .

    # Clean up Docker containers and network
    - name: Clean up Docker container
      run: |
        docker compose down

    # Docker image clean up
    - name: Docker image clean up
      run: |
        docker rmi myapp  # delete image when finished
