name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Set up Docker
    - name: Set up Docker
      run: |
        docker --version
        docker-compose --version || echo "docker-compose not found"

    # Install Docker Compose using official script
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version  # Check Docker Compose version

    # Build and test with Docker Compose
    - name: Run tests
      env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
      run: |
        docker compose build
        docker compose run --rm app pytest -v

    # Lint with flake8
    - name: Lint with flake8
      env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
      run: |
        docker compose up -d  # Start containers in detached mode
        docker compose exec app flake8 .
        docker compose down  # Stop and clean up containers

    # Clean up Docker images
    - name: Docker image clean up
      run: |
        docker rmi myapp || echo "Image already removed"
